# Generated by Django 5.1.4 on 2025-01-14 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0002_perfumes_delete_producto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfumes',
            name='id_vendedor',
        ),
        migrations.AddField(
            model_name='perfumes',
            name='disponible',
            field=models.BooleanField(default='True'),
        ),
        migrations.AddField(
            model_name='perfumes',
            name='id_admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to=settings.AUTH_USER_MODEL),
        ),
    ]
