# Generated by Django 5.1.4 on 2025-01-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=150, unique=True)),
                ('contraseña', models.CharField(max_length=128)),
                ('gmail', models.EmailField(max_length=254, unique=True)),
                ('id_vendedor', models.IntegerField()),
                ('productos_cargados', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
