# Generated by Django 5.1.4 on 2025-01-13 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='id_vendedor',
        ),
    ]
